openapi: 3.0.1
info:
  title: Flink JobManager REST Cluster Datasets API
  contact:
    email: user@flink.apache.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: v1/2.0-SNAPSHOT
tags:
- name: Datasets
paths:
  /datasets:
    get:
      description: Returns all cluster data sets.
      operationId: getClusterDataSetList
      responses:
        '200':
          description: The request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClusterDataSetListResponseBody'
      summary: Apache Flink List Datasets
      tags:
      - Datasets
  /datasets/delete/{triggerid}:
    get:
      description: Returns the status for the delete operation of a cluster data set.
      operationId: getClusterDataSetDeleteStatus
      parameters:
      - name: triggerid
        in: path
        description: 32-character hexadecimal string that identifies an asynchronous operation trigger ID. The ID was returned then the operation was triggered.
        required: true
        schema:
          $ref: '#/components/schemas/TriggerId'
      responses:
        '200':
          description: The request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsynchronousOperationResult'
      summary: Apache Flink Get Datasets Delete
      tags:
      - Datasets
  /datasets/{datasetid}:
    delete:
      description: Triggers the deletion of a cluster data set. This async operation would return a 'triggerid' for further query identifier.
      operationId: deleteClusterDataSet
      parameters:
      - name: datasetid
        in: path
        description: 32-character hexadecimal string value that identifies a cluster data set.
        required: true
        schema:
          $ref: '#/components/schemas/IntermediateDataSetID'
      responses:
        '202':
          description: The request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TriggerResponse'
      summary: Apache Flink Delete Datasets
      tags:
      - Datasets
components:
  schemas:
    QueueStatus:
      required:
      - id
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
    ClusterDataSetEntry:
      type: object
      properties:
        id:
          type: string
        isComplete:
          type: boolean
    TriggerResponse:
      type: object
      properties:
        request-id:
          $ref: '#/components/schemas/TriggerId'
    CheckpointInfo:
      type: object
      properties:
        checkpointId:
          type: integer
          format: int64
        failureCause:
          $ref: '#/components/schemas/SerializedThrowable'
    AsynchronousOperationInfo:
      type: object
      properties:
        failure-cause:
          $ref: '#/components/schemas/SerializedThrowable'
    TriggerId:
      pattern: '[0-9a-f]{32}'
      type: string
    AsynchronousOperationResult:
      type: object
      properties:
        operation:
          oneOf:
          - $ref: '#/components/schemas/AsynchronousOperationInfo'
          - $ref: '#/components/schemas/CheckpointInfo'
          - $ref: '#/components/schemas/SavepointInfo'
        status:
          $ref: '#/components/schemas/QueueStatus'
    Id:
      type: string
      enum:
      - IN_PROGRESS
      - COMPLETED
    IntermediateDataSetID:
      pattern: '[0-9a-f]{32}'
      type: string
    SavepointInfo:
      type: object
      properties:
        failure-cause:
          $ref: '#/components/schemas/SerializedThrowable'
        location:
          type: string
    SerializedThrowable:
      type: object
      properties:
        serialized-throwable:
          type: string
          format: binary
    ClusterDataSetListResponseBody:
      type: object
      properties:
        dataSets:
          type: array
          items:
            $ref: '#/components/schemas/ClusterDataSetEntry'
